#ifndef BSP_GPIO_OUT_H
#define BSP_GPIO_OUT_H

#include "stdint.h"

enum {
    ID_FLITER_PUMP = 0,  // 0
    ID_CLEAN_WATER_VALVE,
    ID_WASTE_WATER_VALVE,
    ID_IO_HUB_CTL_0,
    ID_IO_HUB_CTL_1,
    ID_RK3399_POWER_CTRL,  // 5
    ID_SEWAGE_WATER_VALVE,
    ID_RK_DEBUG_SWITCH_1,
    ID_RK_DEBUG_SWITCH_2,
    ID_LED_POWER,
    ID_MEG_LED,  // 10
    ID_EEPROM_RW,
    ID_COMM_RS485_DE,
    ID_XS_POWER,
    ID_24V_POWER,
    ID_12V_ULT_POWER,  // 15
    ID_ULT_CTRL_0,
    ID_ULT_CTRL_1,
    ID_ULT_CTRL_2,
    ID_KEY_SOFT_ON_LED,
    ID_KEY_SOFT_OFF_LED,  // 20
    ID_KEY_MANUAL_LED,
    ID_KEY_AUTO_LED,
    ID_KEY_CLEAN_LED,
    ID_KEY_DUST_LED,
    ID_KEY_START_LED,  // 25
    ID_KEY_SUSPEND_LED,
    ID_CLEAN_WATER_LEVEL_OK_LED,
    ID_CLEAN_WATER_LEVEL_ERROR_LED,
    ID_WASTE_WATER_LEVEL_OK_LED,
    ID_WASTE_WATER_LEVEL_ERROR_LED,  // 30
    ID_TOF_TMF8X0X_WW_ENABLE_LINE,
    ID_TOF_TMF8X0X_CW_ENABLE_LINE,
    ID_KEY_RETURN_HOME_LED,
    ID_KEY_AUTO_MODE_LED,
    ID_KEY_MANUAL_MODE_LED,  // 35
    ID_KEY_WASH_FLOOR_BLUE_LED,
    ID_KEY_WASH_FLOOR_RED_LED,
    ID_KEY_DUST_PUSH_BLUE_LED,
    ID_KEY_DUST_PUSH_RED_LED,
    ID_KEY_BOARD_POWER_EN
};

void gpio_out_on(uint8_t gpio_out_id);
void gpio_out_off(uint8_t gpio_out_id);
void gpio_out_init_for_pca9539(void);

#endif